version: '3'

services:
  deciderator-server:
    image: 487129032168.dkr.ecr.us-west-2.amazonaws.com/deciderator-server:0.1
    ports:
      - '8080:8080'
    logging:
      driver: awslogs
      options:
        awslogs-group: deciderator
        awslogs-region: us-west-2
        awslogs-stream-prefix: server

  deciderator-app:
    image: 487129032168.dkr.ecr.us-west-2.amazonaws.com/deciderator-app:latest
    ports:
      - '80:80'
      - '443:443'
    logging:
      driver: awslogs
      options:
        awslogs-group: deciderator
        awslogs-region: us-west-2
        awslogs-stream-prefix: app
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=America/Los_Angeles
      - URL=deciderator.app
      - VALIDATION=http
      - EMAIL=deciderator@rik.email
      - SUBDOMAINS=api
      #- STAGING=true
