name: Build/Publish deciderator-app
on:
  push:
    branches:
      - "3.0"
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: rikbrown/deciderator-app # list of Docker images to use as base name for tags
          tag-sha: true # add git short SHA as Docker tag
          tag-latest: true
      - name: Push to Docker Hub
        id: docker_build_push        
        uses: docker/build-push-action@v2
        with:
          push: true  
          context: .
          file: ./Dockerfile-prod-nossl
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
